# Generated by Django 3.2.9 on 2021-11-21 18:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accounttiers',
            old_name='can_choose_expiring_time',
            new_name='choose_exp_time',
        ),
        migrations.RenameField(
            model_name='accounttiers',
            old_name='can_get_link_to_orginal',
            new_name='get_link_to_org',
        ),
        migrations.RemoveField(
            model_name='link',
            name='image',
        ),
        migrations.RemoveField(
            model_name='link',
            name='size',
        ),
        migrations.AddField(
            model_name='link',
            name='expired_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='link',
            name='expiring_time',
            field=models.IntegerField(default=None),
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(upload_to='')),
                ('size', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='images.userplan')),
            ],
        ),
    ]
