# Generated by Django 3.2.9 on 2021-11-21 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0002_auto_20211121_1934'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accounttiers',
            options={'verbose_name_plural': 'AccountTiers'},
        ),
        migrations.RemoveField(
            model_name='image',
            name='size',
        ),
        migrations.AddField(
            model_name='image',
            name='height',
            field=models.IntegerField(null=True),
        ),
    ]
