# Generated by Django 3.2.9 on 2021-11-21 20:33

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0003_auto_20211121_2005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounttiers',
            name='allowed_sizes',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=10), size=None), size=None),
        ),
    ]
