# Generated by Django 3.2.9 on 2021-11-21 21:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0004_alter_accounttiers_allowed_sizes'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='image',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='images.image'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='link',
            name='expiring_time',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
