# Generated by Django 3.2.9 on 2021-11-21 22:22

from django.db import migrations, models
import easy_thumbnails.fields


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0006_auto_20211121_2258'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='headshot',
        ),
        migrations.RemoveField(
            model_name='image',
            name='headshot_ppoi',
        ),
        migrations.AddField(
            model_name='image',
            name='height',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='image',
            name='picture',
            field=easy_thumbnails.fields.ThumbnailerImageField(blank=True, upload_to='photos'),
        ),
    ]
