# Generated by Django 3.2.9 on 2021-11-21 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0007_auto_20211121_2322'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='width',
            field=models.IntegerField(null=True),
        ),
    ]
