# Generated by Django 3.2.9 on 2021-11-22 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0008_image_width'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='expiring_time',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
