# Generated by Django 3.2.9 on 2021-11-24 15:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0011_auto_20211123_1521'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='image_id',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='images.image'),
        ),
    ]
