# Generated by Django 3.2.9 on 2021-11-24 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0012_link_image_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='link',
            name='image_id',
        ),
        migrations.AddField(
            model_name='link',
            name='link_gen',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
